use master 
create database Convalidaciones
GO

use Convalidaciones
GO

create table Alumno(
no_control char(8) primary key,
nombre char(50) not null,
apellidoP char(50) not null,
apellidoM char (50),
semestre smallint not null,
carrera char(80) not null
)

create table Materias(
no_materia char(4) primary key,
clave_materia char (8),
nombre char (80) not null,
carrera char (80) not null,
creditos smallint not null,
)

create table Cursa(
numero_control char (8) Foreign key references Alumno,
clave_materia char (4) Foreign key references Materias,
calificacion float not null,
primary key (numero_control, clave_materia) 
)

create table Convalidaciones(
clave_materia_cursada char (4) Foreign key references Materias,
clave_materia_convalidar char (4) Foreign key references Materias,
no_control char (8) Foreign key references Alumno,
primary key (no_control, clave_materia_cursada, clave_materia_convalidar) 
)
GO


--Ingeniería en Sistemas Computacionales
insert into materias values('0000','ACF-0901 ','Cálculo Diferencial ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0001','AED-1285 ','Fundamentos de Programación ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0002','ACA-0907 ','Taller de Ética ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0003','AEF-1041 ','Matemáticas Discretas ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0004','SCH-1024 ','Taller de Administración ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0005','ACC-0906 ','Fundamentos de Investigación ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0006','ACF-0902 ','Cálculo Integral ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0007','AED-1286 ','Programación Orientada a Objetos ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0008','AEC-1008 ','Contabilidad Financiera ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0009','AEC-1059 ','Química ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0010','ACF-0903 ','Álgebra Lineal ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0011','AEF-1052 ','Probabilidad y Estadística ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0012','ACF-0904 ','Cálculo Vectorial ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0013','AED-1026 ','Estructura de Datos ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0014','SCC-1005 ','Cultura Empresarial ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0015','SCC-1013 ','Investigación de Operaciones ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0016','ACD-0908 ','Desarrollo Sustentable ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0017','SCF-1006 ','Físca General ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0018','ACF-0905 ','Ecuaciones Diferenciales ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0019','SCC-1017 ','Métodos Numéricos ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0020','SCD-1027 ','Tópicos Avanzados de Programación ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0021','AEF-1031 ','Fundamentos de Base de Datos ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0022','SCD-1022 ','Simulación ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0023','SCD-1018 ','Principios Eléctricos y Aplicaciones Digitales ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0024','SCC-1010 ','Graficación ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0025','AEC-1034 ','Fundamentos de Telecomunicaciones ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0026','AEC-1061 ','Sistemas Operativos ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0027','SCA-1025 ','Taller de Base de Datos ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0028','SCC-1007 ','Fundamentos de Ingeniería de Software ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0029','SCD-1003 ','Arquitectura de Computadoras ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0030','SCD-1015 ','Lenguajes y Autómatas I ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0031','SCD-1021 ','Redes de Computadoras ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0032','SCA-1026 ','Taller de Sistemas Operativos ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0033','SCB-1001 ','Administración de Base de Datos ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0034','SCD-1011 ','Ingeniería de Software ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0035','SCC-1014 ','Lenguajes de Interfaz ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0036','SCD-1016 ','Lenguajes y Autómatas II ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0037','SCD-1004 ','Conmutación y Enrutamiento de Redes de Datos ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0038','ACA-0909 ','Taller de Investigación I ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0039','SCG-1009 ','Gestión de Proyectos de Software ', 'Ingeniería en Sistemas Computacionales',6 )
insert into materias values('0040','SCC-1023 ','Sistemas Programables ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0041','SCC-1019 ','Programación Lógica y Funcional ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0042','SCA-1002 ','Administración de Redes ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0043','ACA-0910 ','Taller de Investigación II ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0044','AEB-1055 ','Programación Web ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0045','SCC-1012 ','Inteligencia Artificial ', 'Ingeniería en Sistemas Computacionales',4 )
insert into materias values('0046','  ','Residencias Profesionales', 'Ingeniería en Sistemas Computacionales',10 )
insert into materias values('0047','  ','Especialidad ', 'Ingeniería en Sistemas Computacionales',25 )
insert into materias values('0048','  ','Actividades Complementarias ', 'Ingeniería en Sistemas Computacionales',5 )
insert into materias values('0049','  ','Servicio Social ', 'Ingeniería en Sistemas Computacionales',10 )
--Ingeniería en Tecnologías d00e la Información y Comunicaciones
insert into materias values('0050','ACF-0901 ','Cálculo Diferencial ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0051','AEF-1032 ','Fundamentos de Programación ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0052','TIF-1019 ','Matemáticas Discretas I ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0053','TIP-1017 ','Introducción a las TICs ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',3 )
insert into materias values('0054','ACA-0907 ','Taller de Ética ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0055','ACC-0906 ','Fundamentos de Investigación ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0056','ACF-0902 ','Cálculo Integral ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0057','AEB-1054 ','Programación Orientada a Objetos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0058','TIF-1020 ','Matemáticas Discretas II ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0059','ACF-0903 ','Álgebra Lineal ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0060','AEF-1052 ','Probabilidad y Estadísitca ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0061','TIF-1009 ','Contabilidad y Costos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0062','TID-1012 ','Estructura y Organización de Datos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0063','TIF-1021 ','Matemáticas para la Toma de Decisiones ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0064','AEF-1031 ','Fundamentos de Base de Datos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0065','TIC-1011 ','Electricidad y Magnetismo ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0066','TIC-1002 ','Administración Gerencial ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0067','TIE-1018 ','Matemáticas Aplicadas a Comunicaciones ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0068','TIB-1024 ','Programación II ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0069','TIF-1013 ','Fundamentos de Redes ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0070','AEA-1063 ','Taller de Base de Datos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0071','TID-1008 ','Circuitos Eléctricos y Electrónicos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0072','TIC-1014 ','Ingeniería de Software ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0073','TID-1004 ','Análisis de Señales y Sistemas de Comunicación ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )   
insert into materias values('0074','TIF-1001 ','Administración de Proyectos ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0075','TIF-1025 ','Redes de Computadoras ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0076','TIF-1007 ','Base de Datos Distribuidas ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0077','TIC-1005 ','Arquitectura de Computadoras ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0078','TIC-1027 ','Taller de Ingeniería de Software ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0079','TIF-1029 ','Telecomunicaciones ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0080','AEB-1055 ','Programación Web ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0081','TID-1010 ','Desarrollo de Emprendedores ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0082','AEC-1061 ','Sistemas Operativos I ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0083','ACD-0908 ','Desarrollo Sustentable ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0084','TIC-1028 ','Tecnologías Inalámbricas ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0085','TIF-1026 ','Redes Emergentes ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0086','AEB-1011 ','Desarrollo de Aplicaciones para Dispositivos Móviles ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0087','ACA-0909 ','Taller de Investigación I ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0088','AED-1062 ','Sistemas Operativos II ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0089','TIC-1022 ','Negocios Electrónicos I ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0090','TIH-1016 ','Interacción Humano Computadora ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0091','TIB-1003 ','Administración y Seguridad de Redes ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0092','TIC-1006 ','Auditoria en Tecnologías de la Información ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )       
insert into materias values('0093','ACA-0910 ','Taller de Investigación II ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0094','TIC-1015 ','Ingeniería del Conocimiento ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0095','TIC-1023 ','Negocios Electrónicos II ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',4 )
insert into materias values('0096','  ','Residencias Profesionales ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',10 )
insert into materias values('0097','  ','Especialidad ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',25 )
insert into materias values('0098',' ','Actividades Complementarias ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',5 )
insert into materias values('0099',' ','Servicio Social ', 'Ingeniería en Tecnologías de la Información y Comunicaciones',10 )
--Ingeniería Industrial
insert into materias values('0100','ACC-0906 ','Fundamentos de Investigación ', 'Ingeniería Industrial',4 )
insert into materias values('0101','ACA-0907 ','Taller de Ética ', 'Ingeniería Industrial',4 )
insert into materias values('0102','ACF-0901 ','Cálculo Diferencial ', 'Ingeniería Industrial',5 )
insert into materias values('0103','INH-1029 ','Taller de Herramientas Intelectuales ', 'Ingeniería Industrial',4 )
insert into materias values('0104','INC-1025 ','Química ', 'Ingeniería Industrial',4 )
insert into materias values('0105','INN-1008 ','Dibujo Industrial ', 'Ingeniería Industrial',6 )
insert into materias values('0106','INC-1009 ','Electricidad y Electrónica Industrial ', 'Ingeniería Industrial',4 )
insert into materias values('0107','INC-1024 ','Propiedades de los Materiales ', 'Ingeniería Industrial',4 )
insert into materias values('0108','ACF-0902 ','Cálculo Integral ', 'Ingeniería Industrial',5 )
insert into materias values('0109','AEC-1053 ','Probabilidad y Estadísitca ', 'Ingeniería Industrial',4 )
insert into materias values('0110','INQ-1006 ','Análisis de la Realidad Nacional ', 'Ingeniería Industrial',3 )
insert into materias values('0111','INC-1030 ','Taller de Liderazgo ', 'Ingeniería Industrial',2 )
insert into materias values('0112','AEC-1048 ','Metrología y Normalización ', 'Ingeniería Industrial',4 )
insert into materias values('0113','ACF-0903 ','Álgebra Lineal ', 'Ingeniería Industrial',5 )
insert into materias values('0114','ACF-0904 ','Cálculo Vectorial ', 'Ingeniería Industrial',5 )
insert into materias values('0115','AEC-1018 ','Economía ', 'Ingeniería Industrial',4 )
insert into materias values('0116','AEF-1024 ','Estadística Inferencial I ', 'Ingeniería Industrial',5 )
insert into materias values('0117','INJ-1011 ','Estudio del Trabajo I ', 'Ingeniería Industrial',6 )
insert into materias values('0118','INC-1023 ','Procesos de Fabricación ', 'Ingeniería Industrial',4 )
insert into materias values('0119','INC-1013 ','Física ', 'Ingeniería Industrial',4 )
insert into materias values('0120','INC-1005 ','Algoritmos y Lenguajes de Programación ', 'Ingeniería Industrial',4 )
insert into materias values('0121','INC-1018 ','Investigación de Operaciones I ', 'Ingeniería Industrial',4 )
insert into materias values('0122','AED-1025 ','Estadística Inferencial II ', 'Ingeniería Industrial',5 )
insert into materias values('0123','INJ-1012 ','Estudio del Trabajo II ', 'Ingeniería Industrial',6 )
insert into materias values('0124','INF-1016 ','Higiene y Seguridad Industrial ', 'Ingeniería Industrial',5 )
insert into materias values('0125','INR-1003 ','Administración de Proyectos ', 'Ingeniería Industrial',3 )
insert into materias values('0126','AEC-1392 ','Gestión de Costos ', 'Ingeniería Industrial',4 )
insert into materias values('0127','INC-1001 ','Administración de las Operaciones I ', 'Ingeniería Industrial',4 )
insert into materias values('0128','INC-1019 ','Investigación de Operaciones II ', 'Ingeniería Industrial',4 )
insert into materias values('0129','INF-1007 ','Control Estadístico de la Calidad ', 'Ingeniería Industrial',5 )
insert into materias values('0130','INF-1010 ','Ergonomía ', 'Ingeniería Industrial',5 )
insert into materias values('0131','ACD-0908 ','Desarrollo Sustentable ', 'Ingeniería Industrial',5 )
insert into materias values('0132','ACA-0909 ','Taller de Investigación I ', 'Ingeniería Industrial',4 )
insert into materias values('0133','AEC-1037 ','Ingeniería Económica ', 'Ingeniería Industrial',4 )
insert into materias values('0134','INC-1002 ','Administración de Operaciones II ', 'Ingeniería Industrial',4 )
insert into materias values('0135','INC-1027 ','Simulación ', 'Ingeniería Industrial',4 )
insert into materias values('0136','INC-1004 ','Administración del Mantenimiento ', 'Ingeniería Industrial',4 )
insert into materias values('0137','AED-1044 ','Mercadotecnia ', 'Ingeniería Industrial',5 )
insert into materias values('0138','ACA-0910 ','Taller de Investigación II ', 'Ingeniería Industrial',4 )
insert into materias values('0139','INC-1021 ','Planeación Financiera ', 'Ingeniería Industrial',4 )
insert into materias values('0140','INC-1022 ','Planeación y Diseño de Instalaciones ', 'Ingeniería Industrial',4 )
insert into materias values('0141','INF-1028 ','Sistemas de Manufactura ', 'Ingeniería Industrial',5 )
insert into materias values('0142','INH-1020 ','Logística y Cadenas de Suministro ', 'Ingeniería Industrial',4 )
insert into materias values('0143','INC-1015 ','Gestión de los Sistemas de Calidad ', 'Ingeniería Industrial',4 )
insert into materias values('0144','INR-1017 ','Ingeniería de Sistemas ', 'Ingeniería Industrial',3 )
insert into materias values('0145','AED-1030 ','Formulación y Evaluación de Proyectos ', 'Ingeniería Industrial',5 )
insert into materias values('0146','INC-1026 ','Relaciones Industriales ', 'Ingeniería Industrial',4 )
insert into materias values('0147','  ','Residencias Profesionales ', 'Ingeniería Industrial',10 )
insert into materias values('0148','  ','Especialidad ', 'Ingeniería Industrial',25 )
insert into materias values('0149',' ','Actividades Complementarias ', 'Ingeniería Industrial',5 )
insert into materias values('0150',' ','Servicio Social ', 'Ingeniería Industrial',10 )
--Ingeniería Electrónica	 0
insert into materias values('0151','ACF-0901 ','Cálculo Diferencial ', 'Ingeniería Electrónica',5 )
insert into materias values('0152','AEF-1042 ','Mecánica Clásica ', 'Ingeniería Electrónica',5 )
insert into materias values('0153','AEC-1058 ','Química ', 'Ingeniería Electrónica',4 )
insert into materias values('0154','ACA-0907 ','Taller de Ética ', 'Ingeniería Electrónica',4 )
insert into materias values('0155','ACC-0906 ','Fundamentos de Investigación ', 'Ingeniería Electrónica',4 )
insert into materias values('0156','AEQ-1387 ','Comunicación Humana ', 'Ingeniería Electrónica',3 )
insert into materias values('0157','ACF-0902 ','Cálculo Integral ', 'Ingeniería Electrónica',5 )
insert into materias values('0158','AEE-1051 ','Probabilidad y Estadísitca ', 'Ingeniería Electrónica',4 )
insert into materias values('0159','ACD-0908 ','Desarrollo Sustentable ', 'Ingeniería Electrónica',5 )
insert into materias values('0160','ETD-1021 ','Mediciones Eléctricas ', 'Ingeniería Electrónica',5 )
insert into materias values('0161','ETF-1027 ','Tópicos Selectos de Física ', 'Ingeniería Electrónica',5 )
insert into materias values('0162','ETQ-1009 ','Desarrollo Humano ', 'Ingeniería Electrónica',3 )
insert into materias values('0163','ACF-0904 ','Cálculo Vectorial ', 'Ingeniería Electrónica',5 )
insert into materias values('0164','AEF-1020 ','Electromagnetismo ', 'Ingeniería Electrónica',5 )
insert into materias values('0165','ACF-0903 ','Álgebra Lineal ', 'Ingeniería Electrónica',5 )
insert into materias values('0166','ETF-0903 ','Física de Semiconductores ', 'Ingeniería Electrónica',5 )
insert into materias values('0167','ETD-1024 ','Programación Estructurada ', 'Ingeniería Electrónica',5 )
insert into materias values('0168','ACF-0905 ','Ecuaciones Diferenciales ', 'Ingeniería Electrónica',5 )
insert into materias values('0169','ETF-1004 ','Circuitos Eléctricos I ', 'Ingeniería Electrónica',5 )
insert into materias values('0170','ETP-1020 ','Marco Legal de la Empresa ', 'Ingeniería Electrónica',3 )
insert into materias values('0171','ETF-1003 ','Análisis Numérico ', 'Ingeniería Electrónica',5 )
insert into materias values('0172','ETF-1014 ','Diseño Digital ', 'Ingeniería Electrónica',5 )
insert into materias values('0173','ETD-1025 ','Programación Visual ', 'Ingeniería Electrónica',5 )
insert into materias values('0174','ETF-1005 ','Circuitos Eléctricos II ', 'Ingeniería Electrónica',5 )
insert into materias values('0175','ETF-1012 ','Diodos y Transistores ', 'Ingeniería Electrónica',5 )
insert into materias values('0176','ETF-1026 ','Teoría Electromagnética ', 'Ingeniería Electrónica',5 )
insert into materias values('0177','AEF-1040 ','Máquinas Eléctricas ', 'Ingeniería Electrónica',5 )
insert into materias values('0178','ETF-1015 ','Diseño Digital con VHDL ', 'Ingeniería Electrónica',5 )
insert into materias values('0179','AEO-1388 ','Desarrollo Profesional ', 'Ingeniería Electrónica',3 )
insert into materias values('0180','AEF-1009 ','Control I ', 'Ingeniería Electrónica',5 )
insert into materias values('0181','ETF-1013 ','Diseño con Transistores ', 'Ingeniería Electrónica',5 )
insert into materias values('0182','ETP-1018 ','Fundamentos Financieros ', 'Ingeniería Electrónica',3 )
insert into materias values('0183','ETD-1022 ','Microcontroladores ', 'Ingeniería Electrónica',5 )
insert into materias values('0184','ACA-0909 ','Taller de Investigación I ', 'Ingeniería Electrónica',4 )
insert into materias values('0185','AEF-1010 ','Control II ', 'Ingeniería Electrónica',5 )
insert into materias values('0186','ETF-1002 ','Amplificadores Operacionales ', 'Ingeniería Electrónica',5 )
insert into materias values('0187','AEF-1038 ','Instrumentación ', 'Ingeniería Electrónica',5 )
insert into materias values('0188','ETF-1023 ','Optoelectrónica ', 'Ingeniería Electrónica',5 )
insert into materias values('0189','ETF-1019 ','Introducción a las Telecomunicaciones ', 'Ingeniería Electrónica',5 )
insert into materias values('0190','ACA-0910 ','Taller de Investigación II ', 'Ingeniería Electrónica',4 )
insert into materias values('0191','ETF-1007 ','Control Digital ', 'Ingeniería Electrónica',5 )
insert into materias values('0192','ETF-1008 ','Controladores Lógicos Programables ', 'Ingeniería Electrónica',5 )
insert into materias values('0193','ETF-1016 ','Electrónica de Potencia ', 'Ingeniería Electrónica',5 )
insert into materias values('0194','ETR-1001 ','Administración Gerencial ', 'Ingeniería Electrónica',3 )
insert into materias values('0195','AEO-1389 ','Desarrollo y Evaluación de Proyectos ', 'Ingeniería Electrónica',3 )
insert into materias values('0196','  ','Residencias Profesionales ', 'Ingeniería Electrónica',10 )
insert into materias values('0197','  ','Especialidad ', 'Ingeniería Electrónica',25 )
insert into materias values('0198',' ','Actividades Complementarias ', 'Ingeniería Electrónica',5 )
insert into materias values('0199',' ','Servicio Social ', 'Ingeniería Electrónica',10 )
--Ingeniería Mecatrónica	 0
insert into materias values('0200','AEC-1058 ','Química ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0201','ACF-0901 ','Cálculo Diferencial ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0202','ACA-0907 ','Taller de Ética ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0203','AEA-1013 ','Dibujo Asistido por Computadora ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0204','AEC-1047 ','Mtrología y Normalización ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0205','ACC-0906 ','Fundamentos de Investigación ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0206','ACF-0902 ','Cálculo Integral ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0207','ACF-0903 ','Álgebra Lineal ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0208','MTF-1004 ','Ciencia e Ingeniería de Materiales ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0209','MTD-1024 ','Programación Básica ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0210','MTC-1014 ','Estadística y Control de Calidad ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0211','MTC-1001 ','Administración y Contabilidad ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0212','ACF-0904 ','Cálculo Vectorial ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0213','MTC-1022 ','Procesos de Fabricación ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0214','AEF-1020 ','Electromagnetismo ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0215','MTC-1015 ','Estática ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0216','AEC-1046 ','Métodos Numéricos ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0217','ACD-0908 ','Desarrollo Sustentable ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0218','ACF-0905 ','Ecuaciones Diferenciales ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0219','MTC-1017 ','Fundamentos de Termodinámica ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0220','MTJ-1020 ','Mecánica de Materiales ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0221','MTC-1008 ','Dinámica ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0222','MTJ-1002 ','Análisis de Circuitos Eléctricos ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0223','AEF-1040 ','Máquinas Eléctricas ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0224','MTJ-1011 ','Electrónica Analógica ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0225','AED-1043 ','Mecanismos ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0226','MTC-1003 ','Análisis de Fluidos ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0227','ACA-0909 ','Taller de Investigación I ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0228','MTJ-1012 ','Electrónica de Potencia Aplicada ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0229','AEF-1038 ','Instrumentación ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0230','MTF.1010 ','Diseño de Elementos Mecánicos ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0231','MTF-1013 ','Electrónica Digital ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0232','AED-1067 ','Vibraciones Mecánicas ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0233','ACA-0910 ','Taller de Investigación II ', 'Ingeniería Mecatrónica',4 )
insert into materias values('0234','MTF-1009 ','Dinámicas de Sistemas ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0235','MTD-1019 ','Manufactura Avanzada ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0236','MTG-1005 ','Circuitos Hidráulicos y Neumáticos ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0237','MTF-1018 ','Mantenimiento ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0238','MTF-1021 ','Microcontroladores ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0239','MTG-1023 ','Programación Avanzada ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0240','MTJ-1006 ','Control ', 'Ingeniería Mecatrónica',6 )
insert into materias values('0241','MTO-1016 ','Formulación y Evaluación de Proyectos ', 'Ingeniería Mecatrónica',3 )
insert into materias values('0242','MTD-1007 ','Controladores Lógicos Programables ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0243','MTF-1025 ','Robótica ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0244','  ','Residencias Profesionales ', 'Ingeniería Mecatrónica',10 )
insert into materias values('0245','  ','Especialidad ', 'Ingeniería Mecatrónica',25 )
insert into materias values('0246',' ','Actividades Complementarias ', 'Ingeniería Mecatrónica',5 )
insert into materias values('0247',' ','Servicio Social ', 'Ingeniería Mecatrónica',10 )
--Ingeniería Electromecánica 0
insert into materias values('0248','ACA-0907 ','Taller de Ética ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0249','ACF-0901 ','Cálculo Diferencial ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0250','EMH-1016 ','Introducción a la Programación ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0251','ACD-0908 ','Desarrollo Sustentable ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0252','AEC-1058 ','Química ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0253','ACC-0906 ','Fundamentos de Investigación ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0254','EME-1012 ','Estática ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0255','ACF-0902 ','Cálculo Integral ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0256','ACF-0903 ','Álgebra Lineal ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0257','AEC-1047 ','Metrología y Normalización ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0258','EME-1028 ','Tecnología de los Materiales ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0259','AEF-1390 ','Dibujo Electromecánico ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0260','EME-1008 ','Dinámica ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0261','ACF-0904 ','Cálculo Vectorial ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0262','EMC-1022 ','Procesos de Manufactura ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0263','EMC-1011 ','Electricidad y Magnetismo ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0264','EMJ.1021 ','Mecánica de Materiales ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0265','AEE-1051 ','Probabilidad y Estadística ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0266','EME-1005 ','Análisis y Síntesis de Mecanismos ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0267','ACF-0905 ','Ecuaciones Diferenciales ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0268','EME-1029 ','Termodinámica ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0269','EMF-1004 ','Análisis de Circuitos Eléctricos de CD ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0270','EME-1020 ','Mecánica de Fluidos ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0271','AEF-1021 ','Electrónica Analógica ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0272','EMF-1009 ','Diseño de Elementos de Máquinas ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0273','EMC-1010 ','Diseño e Ingeniería Asistidos por Computadora  ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0274','EME-1030 ','Transferencia de Calor ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0275','EMF-1003 ','Análisis ed Circuitos Electrónicos de CA ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0276','EMJ-1026 ','Sistemas y Máquinas de Fluidos ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0277','AEC-1022 ','Electrónica Digital ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0278','EMC-1018 ','Máquinas y Equipos Térmicos I ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0279','EMJ-1002 ','Ahorro de Energía ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0280','EMF-1015 ','Instalaciones Eléctricas ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0281','EMJ.1017 ','Máquinas Eléctricas ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0282','EMJ.1001 ','Administración y Técnicas de Mantenimiento ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0283','ACA-0909 ','Taller de Investigación I ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0284','EMC-1019 ','Máquinas y Equipos Térmicos II ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0285','EMF-1024 ','Sistemas Eléctricos de Potencia ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0286','EMF-1006 ','Controles Eléctricos ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0287','EMJ-1014 ','Ingeniería de Control Clásico ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0288','ACA-0910 ','Taller de Investigación II ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0289','EMF-1023 ','Refrigeración y Aire Acondicionado ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0290','EMF-1027 ','Subestaciones Eléctricas ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0291','EMJ-1025 ','Sistemas Hidráulicos y Neumáticos de Potencia ', 'Ingeniería Electromecánica ',6 )
insert into materias values('0292','EMC-1013 ','Formulación y Evaluación de Proyectos ', 'Ingeniería Electromecánica ',4 )
insert into materias values('0293','  ','Residencias Profesionales ', 'Ingeniería Electromecánica ',10 )
insert into materias values('0294','  ','Especialidad ', 'Ingeniería Electromecánica ',25 )
insert into materias values('0295',' ','Actividades Complementarias ', 'Ingeniería Electromecánica ',5 )
insert into materias values('0296',' ','Servicio Social ', 'Ingeniería Electromecánica ',10 )
GO
	select * from cursa
	select * from Convalidaciones
	select * from Alumno
	select * from Materias
	GO
